// Auto-generated by scripts/generate-voiceover.mjs — do not edit manually
export const VOICEOVER_MANIFEST = {
  "fps": 30,
  "voice": "en-US-GuyNeural",
  "paddingSeconds": 0.6,
  "scenes": [
    {
      "id": "intro",
      "file": "voiceover/product-demo/intro.mp3",
      "durationInSeconds": 16.416,
      "durationInFrames": 511
    },
    {
      "id": "what",
      "file": "voiceover/product-demo/what.mp3",
      "durationInSeconds": 22.392,
      "durationInFrames": 690
    },
    {
      "id": "pipeline",
      "file": "voiceover/product-demo/pipeline.mp3",
      "durationInSeconds": 31.224,
      "durationInFrames": 955
    },
    {
      "id": "reward",
      "file": "voiceover/product-demo/reward.mp3",
      "durationInSeconds": 29.496,
      "durationInFrames": 903
    },
    {
      "id": "gamify",
      "file": "voiceover/product-demo/gamify.mp3",
      "durationInSeconds": 24.552,
      "durationInFrames": 755
    },
    {
      "id": "outro",
      "file": "voiceover/product-demo/outro.mp3",
      "durationInSeconds": 13.632,
      "durationInFrames": 427
    }
  ],
  "generatedAt": "2026-07-10T06:57:44.443Z"
} as const;
